# Generated by Django 6.1.1 on 2026-10-04 10:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_teacher_user_student_timetablechangelog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DivisionPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("working_days", models.CharField(blank=True, max_length=30)),
                ("first_period", models.PositiveIntegerField(default=1)),
                (
                    "last_period",
                    models.PositiveIntegerField(
                        default=0, help_text="0 means no limit."
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to="scheduler.yeardivision",
                    ),
                ),
            ],
            options={
                "ordering": ["division__year", "division__division_number"],
            },
        ),
        migrations.CreateModel(
            name="ProposedChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ADD_ROOM", "Add a room"),
                            ("RAISE_TEACHER_LIMIT", "Raise a teacher's weekly limit"),
                            (
                                "REASSIGN_TEACHER",
                                "Reassign a subject to another teacher",
                            ),
                            ("REDUCE_HOURS", "Reduce weekly hours"),
                            ("APPLY_PREFERENCES", "Apply timetable preferences"),
                            ("RELAX_UNAVAILABILITY", "Relax teacher unavailability"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "rationale",
                    models.TextField(
                        help_text="Why the engine believes this will resolve the problem."
                    ),
                ),
                ("expected_effect", models.CharField(blank=True, max_length=300)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Awaiting review"),
                            ("APPROVED", "Approved"),
                            ("APPLIED", "Applied and verified"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Applied but did not help"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "verified_gain_hours",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Hours recovered when the remedy was trialled in a sandbox.",
                        null=True,
                    ),
                ),
                ("result_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="scheduler.schedulingissue",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="scheduler.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchedulingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "working_days",
                    models.CharField(
                        default="MON,TUE,WED,THU,FRI",
                        help_text="Comma separated working days.",
                        max_length=30,
                    ),
                ),
                ("day_start_time", models.TimeField(default=datetime.time(9, 0))),
                ("day_end_time", models.TimeField(default=datetime.time(17, 0))),
                ("period_duration_minutes", models.PositiveIntegerField(default=60)),
                ("lunch_start_time", models.TimeField(default=datetime.time(13, 0))),
                ("lunch_end_time", models.TimeField(default=datetime.time(14, 0))),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to="scheduler.semester",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preference_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ISSUE", "Scheduling issue found"),
                            ("PROPOSAL", "A fix is awaiting your approval"),
                            ("TIMETABLE_CHANGED", "Your timetable changed"),
                            ("RESOLVED", "A problem was resolved"),
                            ("SYSTEM", "System message"),
                        ],
                        default="SYSTEM",
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Needs attention"),
                            ("success", "Good news"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=200)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="scheduler.semester",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="scheduler.proposedchange",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="scheduler_n_recipie_b0ae2e_idx",
                    )
                ],
            },
        ),
    ]
