# Generated by Django 6.1.1 on 2026-10-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_divisionpreference_proposedchange_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="scheduler.proposedchange",
            ),
        ),
        migrations.AlterField(
            model_name="proposedchange",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposals",
                to="scheduler.schedulingissue",
            ),
        ),
    ]
