# Generated by Django 6.1.1 on 2026-10-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_alter_notification_proposal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yeardivision",
            name="division_label",
            field=models.CharField(
                default="",
                help_text="Display label for the division (e.g. A, B, N). Defaults to the division number.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="yeardivision",
            name="division_prefix",
            field=models.CharField(
                default="",
                help_text="Name prefix derived from year (SY, TY, SEDA, ...). Auto-filled if blank.",
                max_length=10,
            ),
        ),
    ]
